In [1]:
import sys
sys.path.insert(0, "../Src/")
import generateVoices as gv
import evaluateVoices as ev
import pandas as pd
import os
from os.path import exists
import json
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from pydub import AudioSegment
from TTS.api import TTS
from TTS.utils.manage import ModelManager
import torch
from TTS.utils.radam import RAdam
import numpy.core.multiarray
import shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
import random
import tempfile

torch.serialization.add_safe_globals([RAdam, numpy.core.multiarray.scalar])

%autosave 5

Autosaving every 5 seconds

Autosaving every 5 seconds

Autosaving every 5 seconds

In [2]:
# tts = gv.generateTTS('tts_models/en/ljspeech/vits--neon')
# tts.tts_to_file(
#     text='The anti-slavery movement took many forms.',
#     file_path='test.wav'
# )

In [3]:
def getBestModelName():
    print('starting getBestModelName')
    wordErrorRateResults = pd.read_csv("../Data/wordErrorRateResults.csv")
    bestModel = wordErrorRateResults.sort_values(by="averageWER").iloc[0]
    print('finishing getBestModelName')
    return bestModel["model"]

In [4]:
def getSourceVoice(speaker,speakerDf,datasetName="train"):
    print('starting getSourceVoice')
    if datasetName == "train":
        sourceVoiceFile = f"../Data/concatenatedInputs/{speaker}.wav"
    else:
        sourceVoiceFile = f"../Data/concatenatedTestInputs/{speaker}.wav"
    if exists(sourceVoiceFile):
        print('finishing getSourceVoice')
        return sourceVoiceFile
    gv.concatenateAudio(speaker, speakerDf,datasetName)
    if exists(sourceVoiceFile):
        print('finishing getSourceVoice')
        return sourceVoiceFile
    else:
        print(f"Source voice file for {speaker} not found after concatenation.")
        print('finishing getSourceVoice')
        return None

In [5]:
def getFADJson(datasetName):
    print('starting getFADJson')
    fadJson = []
    if exists(f"../Data/fad_{datasetName}.json"):
        with open(f"../Data/fad_{datasetName}.json", "r") as f:
            fadJson = json.load(f)
    print('finishing getFADJson')
    return fadJson

In [6]:
def saveFADJson(datasetName, fadJson):
    print('starting saveFADJson')
    with open(f"../Data/fad_{datasetName}.json", "w") as f:
        json.dump(fadJson, f)
    print('finishing saveFADJson')

In [7]:
def createFakeAudio(speakerDf, sourceVoice, modelName, datasetName):
    print('starting createFakeAudio')
    fadJson = getFADJson(datasetName)
    textFiles = speakerDf[speakerDf['path_from_data_dir'].str.contains('.TXT', na=False)]
    textFileNames = textFiles['path_from_data_dir'].tolist()

    for textFileName in textFileNames:
        realFile = f"../Data/data/{textFileName.replace('.TXT', '.WAV.wav')}"
        fakeAudioFile = f"../Data/fakeAudio/{textFileName.replace('.TXT', '.wav')}"
        if exists(fakeAudioFile):
            print(f"Fake audio file {fakeAudioFile} already exists.")
            continue
        os.makedirs(os.path.dirname(fakeAudioFile), exist_ok=True)
        model = gv.generateTTS(modelName)
        sentence = gv.readSentenceFromFile(textFileName)
        gv.generateAndNormalizeAudio(model, sentence, sourceVoice, fakeAudioFile)
        if not exists(fakeAudioFile):
            raise FileNotFoundError(f"Failed to create fake audio file: {fakeAudioFile}")
        fadJson.append({
            "file": fakeAudioFile,
            "text": sentence,
            "isFake": True,
        })
        if not exists(realFile):
            raise FileNotFoundError(f"Failed to find real audio file: {realFile}")
        fadJson.append({
            "file": realFile,
            "text": sentence,
            "isFake": False,
        })
        saveFADJson(datasetName,fadJson)
        print('finishing createFakeAudio')

In [8]:
def prepareFADData(modelName,datasetName):
    print('starting prepareFADData')
    print(f"Creating voices for {modelName} on {datasetName} dataset")
    
    df = gv.readCsv(datasetName)
    speakers = gv.getSpeakers(df)
    for speaker in speakers:
        speakerDf = gv.getFilesBySpeaker(df, speaker)
        sourceVoice = getSourceVoice(speaker, speakerDf,datasetName)
        if sourceVoice is None:
            print(f"Skipping {speaker} due to missing source voice.")
            continue
        createFakeAudio(speakerDf, sourceVoice, modelName, datasetName)
    fad_json = getFADJson(datasetName)
    unique_fad_json = [dict(t) for t in {tuple(sorted(d.items())) for d in fad_json}]
    voiceDF = pd.DataFrame(unique_fad_json)
    voiceDF.to_csv(f"../Data/fad_{datasetName}.csv", index=False)
    print('finishing prepareFADData')
    return voiceDF

In [9]:
def main():
    print('starting main')
    bestModelName = getBestModelName()
    trainDF = prepareFADData(bestModelName, 'train')
    testDF =  prepareFADData(bestModelName, 'test')
    display(trainDF.head())
    display(testDF.head())
    print('done')

In [10]:
if __name__ == '__main__':
    main()

starting main
starting getBestModelName
finishing getBestModelName
starting prepareFADData
Creating voices for tts_models/en/ljspeech/vits--neon on train dataset
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SX166.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SX76.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SX346.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SX436.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SI1516.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SI886.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SX256.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FLJD0/SI2146.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SX105.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SI1455.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SX15.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SX375.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SX195.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SI2085.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SI825.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDJM0/SX285.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SX105.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SX15.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SI1635.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SX375.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SI1342.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SI1005.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SX195.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXV0/SX285.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SX262.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SX172.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SI802.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SI2062.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SI1432.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SX352.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SX82.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/FJRP1/SX442.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SX448.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SX358.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SX88.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SX178.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SI808.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SI2068.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SI1438.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR8/FCLT0/SX268.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SI1145.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SX65.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SI1775.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SX155.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SX425.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SX245.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SI515.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FGMB0/SX335.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SX414.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SI2304.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SX144.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SX234.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SX54.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SI1674.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SX324.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MFXS0/SI2225.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SI1293.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SX303.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SX213.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SX393.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SX33.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SI663.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SI1923.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MAPV0/SX123.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SI874.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SX64.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SI2134.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SX347.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SX154.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SX244.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SI1504.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/FSMS1/SX334.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SI1121.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SI1725.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SX401.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SI1751.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SX41.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SX221.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SX24.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MCRE0/SX131.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SX300.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SX210.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SI1830.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SI570.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SX390.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SI1200.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SX120.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MDTB0/SX321.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SX66.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SI786.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SI1416.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SX156.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SX426.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SI2046.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SX246.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/FSKC0/SX336.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SX266.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SI1346.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SI1976.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SX176.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SX86.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SX356.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SI716.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR6/FPAD0/SX446.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SX260.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SX170.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SI2113.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SI980.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SI2240.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SX350.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SX80.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR5/MSDH0/SX440.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SX265.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SI1435.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SI2065.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SX175.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SX85.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SX355.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SX445.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLC1/SI2144.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SX39.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SI1929.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SX129.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SI669.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SX399.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SX219.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SI1299.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MDLR1/SX309.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SX305.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SX215.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SI1205.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SI1215.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SI575.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SX395.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SX125.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MPRB0/SX35.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SI591.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SI1221.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SX411.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SX231.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SX51.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SX141.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SI1851.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR4/MSRG0/SX321.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SX316.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SX406.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SX226.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SX46.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SI1306.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SI676.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SX136.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR2/MDLB0/SI1936.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SI1709.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SX449.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SI1079.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SX359.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SI2339.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SX89.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SX179.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR1/MMGG0/SX269.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SX448.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SI1888.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SX358.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SX88.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SX178.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SI628.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SI1258.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR7/MPFU0/SX268.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SI903.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SI2163.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SX273.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SI807.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SX3.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SX363.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SX93.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MILB0/SX183.wav already exists.
starting getSourceVoice
finishing getSourceVoice
starting createFakeAudio
starting getFADJson
finishing getFADJson
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SX303.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SI454.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SX213.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SA1.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SI1023.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SA2.wav already exists.
Fake audio file ../Data/fakeAudio/TRAIN/DR3/MTKP0/SI2283.wav already exists.

,file,isFake,text
0,../Data/fakeAudio/TRAIN/DR1/FSJK1/SA1.wav,True,She had your dark suit in greasy wash water al...
1,../Data/data/TRAIN/DR5/MREW1/SX420.WAV.wav,False,"Seamstresses attach zippers with a thimble, ne..."
2,../Data/data/TRAIN/DR8/FMBG0/SX80.WAV.wav,False,It's illegal to postdate a check.
3,../Data/fakeAudio/TRAIN/DR2/FCAJ0/SI1804.wav,True,It had gone like clockwork.
4,../Data/data/TRAIN/DR3/FSJW0/SX163.WAV.wav,False,They remain lifelong friends and companions.

,file,isFake,text
0,../Data/fakeAudio/TEST/DR6/MJFC0/SX133.wav,True,Pizzerias are convenient for quick lunch.
1,../Data/fakeAudio/TEST/DR5/MRWS1/SX230.wav,True,"Allow leeway here, but rationalize all errors."
2,../Data/data/TEST/DR5/FJSA0/SI749.WAV.wav,False,Fold into whipped cream and add a dash of salt...
3,../Data/data/TEST/DR2/MABW0/SX314.WAV.wav,False,"If people were more generous, there would be n..."
4,../Data/data/TEST/DR4/MDLS0/SI2258.WAV.wav,False,"You were in a hurry, weren't you?"

done